# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d50a2c51549f244009ca3d22294480b153582fd57bb60262fad0ad901183cabfc1df365c66878c3808d7554dbbafb9cd5abe71ded65af412ab9db0592345bbf9

test:
  secret_key_base: 33c7db01b1e6a0b78bfeacd9163e5cadc4f15d4bc17869631e4736e9c218be431bc842304d764aa286e4587fe3655d97be24a28d4027e6879ed1a41dbd2a1af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
